### ISSUE TITLE
FPS drops when two people in the same party are not in render distance of eachother.

### ISSUE THREAD

**Issue by EpsilonGrimm** [EpsilonWoW/Enteleaie#15]
Aaron and I have been testing this for a bit now, apparently you get weird FPS spikes when you're not in render range of someone in your party.

**Comment by timgblack** [comment]
Can we test this while looking at memory usage?

**Comment by timgblack** [comment]
It appears that RAM usage spikes, which causes the FPS drops. This only happens when somebody else in the party is moving outside of viewdistance (in another phase, according to the group UI). The speed they're moving at doesn't matter.

This is something I'll look into, but not something I'm able to give an ETA on fixing.

**Comment by AddieA** [comment]
It only appears to be happening if you look in the direction where the person is? Further testing/confirmation might be required.
