### ISSUE TITLE
Spell 27: Goldshire Portal

### ISSUE THREAD

**Issue by zennironbeard** [EpsilonWoW/Enteleaie#16]
Not particularly too visually disturbing, but it spawns a single blue checkered cube when casted.

**Comment by Aarontravess** [comment]
This could be something to do with the expansion problem, if the assets needed for the visual of the object are contained in any of the 'expansion' mpq's they don't seem to work if you don't have the expansions enabled. I figured this when I spawned some Dalaran buildings and they were radioactive green because I didn't have the wotlk expansion available.

**Comment by ever0n** [comment]
Even with expansions enabled the spell still creates a debug cube.

**Comment by timgblack** [comment]
We will start restricting/banning spells in the Open Beta Testing period.
