### ISSUE TITLE
[Patch Feature] Expanded Character Creation

### ISSUE THREAD

**Issue by DavidTwo** [EpsilonWoW/Enteleaie#46]
Something that one of the former Patch-P members did was create something for the "final" Patch-P (at the time), allowing us to create characters with all of the available skins in the game, including the Death Knight skins. This should make a return.

**Comment by MindScape00** [comment]
I believe I still have all the work on this.. Should be in the stuff that they have already also.

**Comment by DavidTwo** [comment]
I think I have that patch as well. I was talking to Grimm about it over Skype yesterday and he told me to post this *shrug*

**Comment by Kalrihk** [comment]
This would require both Patch and DBC work.

I'm pretty sure that doing this would also cut down on some of the space used in the patches, so instead of having to .mod displayid(2) in to something, you can just change it via command/account tools.

There might be the risk of nude bugs and crashing, however - things that can be ironed out.

(Also noticed that this can sometimes cause reverse textures, disappearing armor or weapons, and floating body parts in 4.0.1-4.2x)
